apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xawsvms.customer.upbound.io
spec:
  compositeTypeRef:
    apiVersion: customer.upbound.io/v1alpha1
    kind: XAwsVm
  mode: Pipeline
  pipeline:
  - functionRef:
      name: upbound-demo-aws-vmaws-vm
    step: aws-vm
  - functionRef:
      name: crossplane-contrib-function-auto-ready
    step: crossplane-contrib-function-auto-ready
