apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xawsvms.customer.upbound.io
spec:
  claimNames:
    kind: AwsVm
    plural: awsvms
  group: customer.upbound.io
  names:
    categories:
    - crossplane
    kind: XAwsVm
    plural: xawsvms
  versions:
  - name: v1alpha1
    referenceable: true
    schema:
      openAPIV3Schema:
        description: AwsVm is the Schema for the AwsVm API.
        properties:
          spec:
            description: AwsVmSpec defines the desired state of AwsVm.
            properties:
              parameters:
                properties:
                  ami:
                    type: string
                  instanceType:
                    type: string
                  region:
                    type: string
                type: object
            type: object
          status:
            description: AwsVmStatus defines the observed state of AwsVm.
            type: object
        required:
        - spec
        type: object
    served: true
